### ISSUE TITLE
Issue with the prepared PI images

### ISSUE THREAD

**Issue by SleepyBrett** [guysoft/OctoPi#405]
It looks like there may be an issue with the automated build. Both 2017-08-19_2017-08-16-octopi-stretch-lite-0.15.zip and 2017-06-25_2017-06-21-octopi-jessie-lite-0.14.0.zip produce the following error when I attempt to restore them onto a 32gb card using Apple PI Baker.

<img width="480" alt="screen shot 2017-08-26 at 11 31 56 am" src="https://user-images.githubusercontent.com/279521/29744110-cdcec19a-8a52-11e7-8d9d-12dd6365a64c.png">

If I click through the error it claims to have written the file in a little under a minute and it, of course does not boot.

I also made an attempt to write it with dd `sudo dd bs=1m if=2017-08-16-octopi-stretch-lite-0.15.img of=/dev/disk2 conv=sync` also completes in about 20s with the following output:

    dd: /dev/disk2: end of device
    31+0 records in
    30+1 records out
    32100352 bytes transferred in 4.729115 secs (6787814 bytes/sec)

**Comment by ntoff** [comment]
Did you try checking the hash of the zip file to make sure it downloaded properly? `2017-08-19_2017-08-16-octopi-stretch-lite-0.15.zip` seems to write to SD fine here (using win32 disk imager), although I do think something is severely broken with the stretch build because a fresh install and boot and neither haproxy, nor webcamd, nor the octoprint service are running for me on my raspberry pi3. But besides that, the image itself doesn't seem to be corrupted.

**Comment by SleepyBrett** [comment]
Pretty sure it's just a bad card, headed to the corner now to pick up a new one to test.

**Comment by SleepyBrett** [comment]
Yup, my bad, failed card.
