### ISSUE TITLE
Octopi wlan0 always gets APIPA IP address (169.254)

### ISSUE THREAD

**Issue by S1llyB01** [guysoft/OctoPi#502]
.

**Comment by guysoft** [comment]
Does it do the same thing with plain Raspbian?

**Comment by whodatwh0dat** [comment]
@guysoft no, I always get an IP.

**Comment by btwood** [comment]
I believe that CIDR is used by some systems, including windows, if a DHCP server could not be reached.

Try relocating your Pi, and ensuring you've got a good network connection. Try changing your wireless router to "auto" channel selection, and reboot it in order to switch to a wifi channel that isn't as saturated.

Make sure you don't have any other wireless interference going on, such as neighbors, poorly shielded microwaves, dead-zones, other clients. Ultimately a direct line of sight between the client and the router is best. Make sure the wireless signal doesn't have to go through a lot of walls/metal/shielding in order to reach the router.

Lastly, the Zero W uses 802.11n, which means it's going to be 2.5 GHz only. You might be able to get better network performance if you buy an extrernal USB dongle that does 5 GHz if your router supports it and your printer isn't too far away from your router.

There are certainly other ways to solve this issue, including trying to create a wireless mesh in your house, but that is probably well beyond the scope of cost and reason for most people.

Another option is to add an external antenna, but that requires some soldering and some understanding of the board schematic. In theory a fixed wire could work just as well, but I honestly don't know.
https://www.briandorey.com/post/Raspberry-Pi-Zero-W-external-antenna-mod

**Comment by guysoft** [comment]
Strange actions by reporter, tried to destroy his report. Closing because I don't know why.
