### ISSUE TITLE
Issues with latest 0.16 build and Logitech C270 Camera

### ISSUE THREAD

**Issue by MrJabu** [guysoft/OctoPi#585]
i think there is a issue with the latest build. i could not get the c270 working for the life of me. i messed with default settings and changing octopi.txt & config.txt parameters. nothing worked.

i then loaded the 0.15 image and everything worked right away without having to change anything.

**Comment by guysoft** [comment]
Output of ``dmesg`` command when you plug it in? Might get more info from
the driver.

**Comment by guysoft** [comment]
Might be related to: https://github.com/guysoft/OctoPi/issues/499

**Comment by podmore71** [comment]
Having the same issue recently. Sometimes it works, other times it doesn't.  at first I was using a ps3 webcam and thought that might be the problem so I bought the C270, but it's still doing it. Here is the output of the 'dmesg'

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.19.42-v7+ (dom@dom-XPS-13-9370) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1219 SMP Tue May 14 21:20:58 BST 2019
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x37800000
[    0.000000] On node 0 totalpages: 229376
[    0.000000]   Normal zone: 2016 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 229376 pages, LIFO batch:63
[    0.000000] random: get_random_bytes called from start_kernel+0xac/0x4b4 with crng_init=0
[    0.000000] percpu: Embedded 17 pages/cpu s39488 r8192 d21952 u69632
[    0.000000] pcpu-alloc: s39488 r8192 d21952 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 227360
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=d86f492f-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 886308K/917504K available (8192K kernel code, 627K rwdata, 2164K rodata, 1024K init, 821K bss, 23004K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xb8800000 - 0xff800000   (1136 MB)
                   lowmem  : 0x80000000 - 0xb8000000   ( 896 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (9184 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   (1024 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 628 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 822 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 26229 entries in 77 pages
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000022] Switching to timer-based delay loop, resolution 52ns
[    0.000287] Console: colour dummy device 80x30
[    0.000907] console [tty1] enabled
[    0.000963] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.001008] pid_max: default: 32768 minimum: 301
[    0.001364] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001401] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002331] CPU: Testing write buffer coherency: ok
[    0.002806] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.003479] Setting up static identity map for 0x100000 - 0x10003c
[    0.003645] rcu: Hierarchical SRCU implementation.
[    0.004454] smp: Bringing up secondary CPUs ...
[    0.005314] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.006241] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.007103] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.007223] smp: Brought up 1 node, 4 CPUs
[    0.007304] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.007328] CPU: All CPU(s) started in HYP mode.
[    0.007348] CPU: Virtualization extensions available.
[    0.008336] devtmpfs: initialized
[    0.020127] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.020396] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.020444] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.021048] pinctrl core: initialized pinctrl subsystem
[    0.021938] NET: Registered protocol family 16
[    0.024915] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.030659] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.030696] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.030929] Serial: AMBA PL011 UART driver
[    0.033201] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.068203] bcm2835-dma 3f007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.069891] SCSI subsystem initialized
[    0.070186] usbcore: registered new interface driver usbfs
[    0.070263] usbcore: registered new interface driver hub
[    0.070375] usbcore: registered new device driver usb
[    0.090114] raspberrypi-firmware soc:firmware: Attached to firmware from 2019-03-27 15:48, variant start_x
[    0.100356] raspberrypi-firmware soc:firmware: Firmware hash is 2e98b31d18547962e564bdf88e57b3df7085c29b
[    0.111730] clocksource: Switched to clocksource arch_sys_counter
[    0.200401] VFS: Disk quotas dquot_6.6.0
[    0.200511] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.200753] FS-Cache: Loaded
[    0.200986] CacheFiles: Loaded
[    0.210992] NET: Registered protocol family 2
[    0.211854] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes)
[    0.211920] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.212064] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.212270] TCP: Hash tables configured (established 8192 bind 8192)
[    0.212427] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.212497] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.212849] NET: Registered protocol family 1
[    0.213454] RPC: Registered named UNIX socket transport module.
[    0.213480] RPC: Registered udp transport module.
[    0.213502] RPC: Registered tcp transport module.
[    0.213523] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.215162] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.218233] Initialise system trusted keyrings
[    0.218437] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.228250] FS-Cache: Netfs 'nfs' registered for caching
[    0.228838] NFS: Registering the id_resolver key type
[    0.228886] Key type id_resolver registered
[    0.228908] Key type id_legacy registered
[    0.228940] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.231241] Key type asymmetric registered
[    0.231269] Asymmetric key parser 'x509' registered
[    0.231336] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    0.231526] io scheduler noop registered
[    0.231550] io scheduler deadline registered (default)
[    0.231833] io scheduler cfq registered
[    0.231857] io scheduler mq-deadline registered (default)
[    0.231881] io scheduler kyber registered
[    0.234533] BCM2708FB: allocated DMA memory 0xf7900000
[    0.234596] BCM2708FB: allocated DMA channel 0
[    0.243225] Console: switching to colour frame buffer device 82x26
[    0.251938] bcm2835-rng 3f104000.rng: hwrng registered
[    0.254349] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.259419] vc-sm: Videocore shared memory driver
[    0.262062] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.277632] brd: module loaded
[    0.290130] loop: module loaded
[    0.292553] Loading iSCSI transport class v2.0-870.
[    0.295615] libphy: Fixed MDIO Bus: probed
[    0.298030] usbcore: registered new interface driver lan78xx
[    0.300405] usbcore: registered new interface driver smsc95xx
[    0.302644] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.332762] dwc_otg 3f980000.usb: base=(ptrval)
[    0.535228] Core Release: 2.80a
[    0.537446] Setting default values for core params
[    0.539729] Finished setting default values for core params
[    0.742337] Using Buffer DMA mode
[    0.744611] Periodic Transfer Interrupt Enhancement - disabled
[    0.747012] Multiprocessor Interrupt Enhancement - disabled
[    0.749398] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.751763] Dedicated Tx FIFOs mode
[    0.754491] WARN::dwc_otg_hcd_init:1045: FIQ DMA bounce buffers: virt = b7914000 dma = 0xf7914000 len=9024
[    0.759077] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.770006] dwc_otg: Microframe scheduler enabled
[    0.770068] WARN::hcd_init_fiq:457: FIQ on core 1
[    0.772302] WARN::hcd_init_fiq:458: FIQ ASM at 8064b6dc length 36
[    0.774518] WARN::hcd_init_fiq:484: MPHI regs_base at f0006000
[    0.776825] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.779089] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.781410] dwc_otg 3f980000.usb: irq 56, io mem 0x00000000
[    0.783741] Init: Port Power? op_state=1
[    0.785983] Init: Power Port (0)
[    0.788398] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    0.792926] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.795340] usb usb1: Product: DWC OTG Controller
[    0.797707] usb usb1: Manufacturer: Linux 4.19.42-v7+ dwc_otg_hcd
[    0.800126] usb usb1: SerialNumber: 3f980000.usb
[    0.803099] hub 1-0:1.0: USB hub found
[    0.805382] hub 1-0:1.0: 1 port detected
[    0.808131] dwc_otg: FIQ enabled
[    0.808137] dwc_otg: NAK holdoff enabled
[    0.808142] dwc_otg: FIQ split-transaction FSM enabled
[    0.808153] Module dwc_common_port init
[    0.808429] usbcore: registered new interface driver usb-storage
[    0.810887] mousedev: PS/2 mouse device common for all mice
[    0.814078] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.816805] bcm2835-cpufreq: min=600000 max=1400000
[    0.819658] sdhci: Secure Digital Host Controller Interface driver
[    0.822122] sdhci: Copyright(c) Pierre Ossman
[    0.824926] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.827864] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.830553] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.834704] ledtrig-cpu: registered to indicate activity on CPUs
[    0.837462] hidraw: raw HID events driver (C) Jiri Kosina
[    0.840258] usbcore: registered new interface driver usbhid
[    0.842943] usbhid: USB HID core driver
[    0.846264] vchiq: vchiq_init_state: slot_zero = (ptrval), is_master = 0
[    0.850378] [vc_sm_connected_init]: start
[    0.859165] [vc_sm_connected_init]: end - returning 0
[    0.862696] Initializing XFRM netlink socket
[    0.865153] NET: Registered protocol family 17
[    0.867687] Key type dns_resolver registered
[    0.870551] Registering SWP/SWPB emulation handler
[    0.873707] registered taskstats version 1
[    0.876142] Loading compiled-in X.509 certificates
[    0.885866] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.888407] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.895189] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.897720] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.925085] sdhost: log_buf @ (ptrval) (f7913000)
[    0.964902] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.968866] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.972725] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.976091] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.979557] of_cfs_init
[    0.981840] of_cfs_init: OK
[    0.984454] Waiting for root device PARTUUID=d86f492f-02...
[    0.999750] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    1.021849] Indeed it is in host mode hprt0 = 00021501
[    1.093772] random: fast init done
[    1.120514] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.128597] mmc0: new high speed SDHC card at address aaaa
[    1.133775] mmcblk0: mmc0:aaaa SC16G 14.8 GiB
[    1.139978] mmc1: new high speed SDIO card at address 0001
[    1.142863]  mmcblk0: p1 p2
[    1.174798] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.179326] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.189805] devtmpfs: mounted
[    1.198061] Freeing unused kernel memory: 1024K
[    1.202172] Run /sbin/init as init process
[    1.231775] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.234494] Indeed it is in host mode hprt0 = 00001101
[    1.472078] usb 1-1: New USB device found, idVendor=0424, idProduct=2514, bcdDevice= b.b3
[    1.477440] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.480975] hub 1-1:1.0: USB hub found
[    1.483982] hub 1-1:1.0: 4 ports detected
[    1.661104] systemd[1]: System time before build time, advancing clock.
[    1.791868] NET: Registered protocol family 10
[    1.795930] Segment Routing with IPv6
[    1.811779] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.828573] random: systemd: uninitialized urandom read (16 bytes read)
[    1.833877] random: systemd: uninitialized urandom read (16 bytes read)
[    1.842171] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.851021] systemd[1]: Detected architecture arm.
[    1.881851] systemd[1]: Set hostname to <edff3d>.
[    1.933239] random: systemd-cryptse: uninitialized urandom read (16 bytes read)
[    1.942199] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514, bcdDevice= b.b3
[    1.947865] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.962464] hub 1-1.1:1.0: USB hub found
[    1.965574] hub 1-1.1:1.0: 3 ports detected
[    2.071805] usb 1-1.3: new full-speed USB device number 4 using dwc_otg
[    2.205545] usb 1-1.3: New USB device found, idVendor=1d50, idProduct=6029, bcdDevice= 1.00
[    2.210863] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.213709] usb 1-1.3: Product: Marlin USB Device
[    2.216451] usb 1-1.3: Manufacturer: marlinfw.org
[    2.219235] usb 1-1.3: SerialNumber: 04006015AF3620855B695ECCF50020C5
[    2.223458] usb-storage 1-1.3:1.2: USB Mass Storage device detected
[    2.227249] scsi host0: usb-storage 1-1.3:1.2
[    2.301793] usb 1-1.1.3: new high-speed USB device number 5 using dwc_otg
[    2.437758] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.447464] systemd[1]: Listening on Journal Socket.
[    2.454023] systemd[1]: Listening on fsck to fsckd communication Socket.
[    2.460602] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.467711] systemd[1]: Created slice System Slice.
[    2.480466] systemd[1]: Starting Restore / save the current clock...
[    2.492816] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    2.644080] usb 1-1.1.3: New USB device found, idVendor=046d, idProduct=0825, bcdDevice= 0.10
[    2.648186] usb 1-1.1.3: New USB device strings: Mfr=0, Product=0, SerialNumber=2
[    2.652492] usb 1-1.1.3: SerialNumber: 30675FD0
[    2.951918] usb 1-1.1.1: new high-speed USB device number 6 using dwc_otg
[    3.033885] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    3.082526] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800, bcdDevice= 3.00
[    3.082541] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.130024] systemd-journald[112]: Received request to flush runtime journal from PID 1
[    3.276080] scsi 0:0:0:0: Direct-Access     Marlin   SDCard 01        1.0  PQ: 0 ANSI: 0 CCS
[    3.279169] sd 0:0:0:0: [sda] 245760 512-byte logical blocks: (126 MB/120 MiB)
[    3.294002] sd 0:0:0:0: [sda] Write Protect is off
[    3.294021] sd 0:0:0:0: [sda] Mode Sense: 00 00 00 00
[    3.297384] sd 0:0:0:0: [sda] Asking for cache data failed
[    3.297400] sd 0:0:0:0: [sda] Assuming drive cache: write through
[    3.323899]  sda: sda1
[    3.335559] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    3.348509] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): No External EEPROM. Setting MAC Speed
[    3.349604] libphy: lan78xx-mdiobus: probed
[    3.363278] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): int urb period 64
[    3.438866] media: Linux media interface: v0.10
[    3.475822] videodev: Linux video capture interface: v2.00
[    3.554474] uvcvideo: Found UVC 1.00 device <unnamed> (046d:0825)
[    3.563820] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    3.675093] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 4 was not initialized!
[    3.675111] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 6 was not initialized!
[    3.675123] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 7 was not initialized!
[    3.675135] uvcvideo 1-1.1.3:1.0: Entity type for entity Processing 2 was not initialized!
[    3.675147] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 3 was not initialized!
[    3.675159] uvcvideo 1-1.1.3:1.0: Entity type for entity Camera 1 was not initialized!
[    3.675567] input: UVC Camera (046d:0825) as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3/1-1.1.3:1.0/input/input0
[    3.675877] usbcore: registered new interface driver uvcvideo
[    3.675884] USB Video Class driver (1.1.1)
[    4.067931] random: crng init done
[    4.067943] random: 7 urandom warning(s) missed due to ratelimiting
[    4.835834] usb 1-1.1.3: set resolution quirk: cval->res = 384
[    4.836634] usbcore: registered new interface driver snd-usb-audio
[    8.337757] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[    8.340807] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[    8.342816] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[    8.342838] [vc_sm_connected_init]: start
[    8.347620] [vc_sm_connected_init]: installed successfully
[    8.350696] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    8.353323] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    8.364438] bcm2835_audio soc:audio: card created with 8 channels
[    8.379154] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[    8.384309] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[    8.503911] usbcore: registered new interface driver uas
[    8.535284] cdc_acm 1-1.3:1.0: ttyACM0: USB ACM device
[    8.536400] usbcore: registered new interface driver cdc_acm
[    8.536411] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[    8.593309] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    8.673419] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    8.764071] brcmfmac: F1 signature read @0x18000000=0x15264345
[    8.770314] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    8.770765] usbcore: registered new interface driver brcmfmac
[    8.842169] usb 1-1.1.3: reset high-speed USB device number 5 using dwc_otg
[    9.016992] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    9.017012] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    9.029968] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.031597] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    9.031611] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    9.037480] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    9.037495] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    9.063624] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[    9.892567] uart-pl011 3f201000.serial: no DMA platform data
[   10.212998] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.213254] brcmfmac: power management disabled
[   10.315099] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   10.730176] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   10.750859] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   16.317079] Bluetooth: Core ver 2.22
[   16.317132] NET: Registered protocol family 31
[   16.317136] Bluetooth: HCI device and connection manager initialized
[   16.317151] Bluetooth: HCI socket layer initialized
[   16.317158] Bluetooth: L2CAP socket layer initialized
[   16.317179] Bluetooth: SCO socket layer initialized
[   16.331908] Bluetooth: HCI UART driver ver 2.3
[   16.331916] Bluetooth: HCI UART protocol H4 registered
[   16.331960] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   16.332073] Bluetooth: HCI UART protocol Broadcom registered
[   16.532875] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   16.532882] Bluetooth: BNEP filters: protocol multicast
[   16.532895] Bluetooth: BNEP socket layer initialized

**Comment by guysoft** [comment]
Related:
https://community.octoprint.org/t/issue-with-rpi-3-and-logitech-c270-camera/9091

This is the relevant output from your dmesg:
```
[ 3.475822] videodev: Linux video capture interface: v2.00
[ 3.554474] uvcvideo: Found UVC 1.00 device (046d:0825)
[ 3.563820] sd 0:0:0:0: Attached scsi generic sg0 type 0
[ 3.675093] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 4 was not initialized!
[ 3.675111] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 6 was not initialized!
[ 3.675123] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 7 was not initialized!
[ 3.675135] uvcvideo 1-1.1.3:1.0: Entity type for entity Processing 2 was not initialized!
[ 3.675147] uvcvideo 1-1.1.3:1.0: Entity type for entity Extension 3 was not initialized!
[ 3.675159] uvcvideo 1-1.1.3:1.0: Entity type for entity Camera 1 was not initialized!
[ 3.675567] input: UVC Camera (046d:0825) as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3/1-1.1.3:1.0/input/input0
[ 3.675877] usbcore: registered new interface driver uvcvideo
[ 3.675884] USB Video Class driver (1.1.1)
```

Looks like  its detected,  Do you have any ``/dev/video0`` file?

**Comment by podmore71** [comment]
Thanks for the quick reply. There is a file named video0 in the /dev folder

Andy

**Comment by podmore71** [comment]
Just had a quick power cut and on restart it's working again but don't know how long it will last

**Comment by podmore71** [comment]
So I came back to it this afternoon and low and behold, it did it again. I'm running Octopi ver 0.16 and Octoprint 1.3.11. I even tried installing 0.15.1 with 1.3.11 and it still did it, although it is currently working now. It's a very strange and intermittent problem

**Comment by guysoft** [comment]
So is this fixed? Can I close this?
