### ISSUE TITLE
[Question] Building location

### ISSUE THREAD

**Issue by miathedev** [guysoft/OctoPi#736]
"We recently had to move to building location, donations for somewhere with HTTPS would be great."

What excactly does OctoPi need? I and my fellow students run a little cluster together. Im sure we have free ressources. If you tell me what is needed. I try to make it happen. Https - no problem at all.

With kind regards,
Mia

**Comment by guysoft** [comment]
Hey,
Thanks for the offer. At the moment I got a donation from https://unofficialpi.org/Distros/OctoPi/ and https://octopi.gnethomelinux.com/Distros/OctoPi/ .
I still didn't finish mirroring the latter automatically. But two mirrors good enough because it means if one dies there is a replication.

Also I am not sure I want to base the system on something students run, because their time is likely limited to handle this. And so far our mirrors held for ~5 years which is hopefully more then the time it takes for them to do their degree.
