### ISSUE TITLE
Change verbiage to allow/deny list

### ISSUE THREAD

**Issue by PacificState** [guysoft/OctoPi#768]
I'm setting up octopi for the first time via the browser, and got to the 'Configure plugin blacklist processing' page. Can this be changed to 'Configure plugin deny list processing' instead?

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue. It should be posted to OctoPrint issue tracker at: https://github.com/OctoPrint/OctoPrint/issues

You might want to suggest "blocked plugin list" since the word "deny" is usually associated with networking. It would make more sense and gives a better chance for the change to be accepted.
